# Application Configuration
# ============================
management:
  context-path: "/jms"
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

aws:
  host: http://localhost:4000